services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: eccountant
      POSTGRES_PASSWORD: eccountant
      POSTGRES_DB: eccountant
    volumes:
      - /postgres_data:/var/lib/postgresql/data
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
