services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: eccountant
      POSTGRES_PASSWORD: eccountant
      POSTGRES_DB: eccountant
    volumes:
      # - /postgres_data:/var/lib/postgresql/data
      # - /var/lib/docker/volumes/postgres_volume/_data:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
      # - /var/lib/postgresql/data
    ports:
      - "5555:5432"

volumes:
  postgres_data: