name: Publish and Deploy Eccountant

on:
  push:
    branches:
      - main
    paths:
      - web/**
      - backend/**
      - common/**
      - docker-compose.prod.yml
      - .github/workflows/*

env:
  FRONTEND_IMAGE_NAME: eccountant-web
  BACKEND_IMAGE_NAME: eccountant-backend

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    environment: web # Specify the environment for frontend

    steps:
      - uses: actions/checkout@v2

      - name: Ensure environment.ts exists
        working-directory: web
        run: |
          if [ ! -f src/environments/environment.ts ]; then
            echo "export const environment = { production: false };" > src/environments/environment.ts
            echo "export default environment;" >> src/environments/environment.ts
          fi

      - name: Create environment.prod.ts
        working-directory: web
        run: |
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  auth0_audience: '${{ secrets.AUTH0_AUDIENCE }}'," >> src/environments/environment.prod.ts
          echo "  auth0_domain: '${{ secrets.AUTH0_DOMAIN }}'," >> src/environments/environment.prod.ts
          echo "  auth0_client_id: '${{ secrets.AUTH0_CLIENT_ID }}'," >> src/environments/environment.prod.ts
          echo "  api_url: '${{ secrets.API_URL }}'," >> src/environments/environment.prod.ts
          # Add any other environment variables here
          echo "};" >> src/environments/environment.prod.ts
          echo "export default environment;" >> src/environments/environment.prod.ts

      - name: Build frontend image
        run: |
          docker build -t $FRONTEND_IMAGE_NAME -f web/Dockerfile .

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push frontend image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$FRONTEND_IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $FRONTEND_IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  build-and-push-backend:
    runs-on: ubuntu-latest
    environment: backend # Specify the environment for backend

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        working-directory: backend
        run: |
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "WEBHOOK_PORT=${{ secrets.WEBHOOK_PORT }}" >> .env
          echo "PLAID_CLIENT_NAME=${{ secrets.PLAID_CLIENT_NAME }}" >> .env
          echo "PLAID_CLIENT_ID=${{ secrets.PLAID_CLIENT_ID }}" >> .env
          echo "PLAID_SECRET=${{ secrets.PLAID_SECRET }}" >> .env
          echo "PLAID_PRODUCTS=${{ secrets.PLAID_PRODUCTS }}" >> .env
          echo "PLAID_COUNTRY_CODES=${{ secrets.PLAID_COUNTRY_CODES }}" >> .env
          echo "PLAID_WEBHOOK_URL=${{ secrets.PLAID_WEBHOOK_URL }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}" >> .env
          echo "AUTH0_SECRET=${{ secrets.AUTH0_SECRET }}" >> .env
          echo "AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}" >> .env

      - name: Build backend main server image
        run: |
          docker build -t $BACKEND_IMAGE_NAME -f backend/Dockerfile .

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push backend main server image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$BACKEND_IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $BACKEND_IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  deploy-to-vm:
    runs-on: ubuntu-latest

    needs: [build-and-push-frontend, build-and-push-backend] # Ensure this job runs after the build jobs

    steps:
      - uses: actions/checkout@v2

      - name: Copy Docker Compose file to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.prod.yml"
          target: "eccountant"

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd eccountant || exit 1
            sudo docker compose -f docker-compose.prod.yml pull || exit 1
            sudo docker compose -f docker-compose.prod.yml up -d || exit 1
            # Run Prisma migrations
            sudo docker compose -f docker-compose.prod.yml exec backend npx prisma migrate deploy || exit 1
            sudo docker compose -f docker-compose.prod.yml exec webhook npx prisma migrate deploy || exit 1
