name: Deploy Docker Compose

on:
  workflow_run:
    workflows: ["Publish Angular Skeleton to GHCR", "Publish Express Skeleton to GHCR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy and rename Docker Compose file to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.prod.yml"
          target: "eccountant/docker-compose.yml"

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd eccountant
            sudo docker-compose pull
            sudo docker-compose up -d
            # Run Prisma migrations
            sudo docker-compose exec backend npx prisma migrate deploy