name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - web/**
      - backend/**

jobs:
  # lint-frontend:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: web
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '20'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Lint
  #       run: npm run lint

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Ensure environment.ts exists
        run: |
          if [ ! -f src/environments/environment.ts ]; then
            echo "const environment = { production: false };" > src/environments/environment.ts
            echo "export default environment;" >> src/environments/environment.ts
          fi

      - name: Create environment.prod.ts
        run: |
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  auth0_audience: '${{ secrets.AUTH0_AUDIENCE }}'," >> src/environments/environment.prod.ts
          echo "  auth0_domain: '${{ secrets.AUTH0_DOMAIN }}'," >> src/environments/environment.prod.ts
          echo "  auth0_client_id: '${{ secrets.AUTH0_CLIENT_ID }}'," >> src/environments/environment.prod.ts
          echo "  api_url: '${{ secrets.PROD_API_URL }}'," >> src/environments/environment.prod.ts
          # Add any other environment variables here
          echo "};" >> src/environments/environment.prod.ts
          echo "export default environment;" >> src/environments/environment.prod.ts

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --configuration=production

  # lint-backend:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: backend
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '20'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Lint
  #       run: npm run lint

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
